version: '3'
services:
  web-content-api:
    container_name: web-content-management-api
    build: .
    ports:
      - "8090:8090"
    restart: always

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - /opt/projects/teach/upload/images:/opt/projects/teach/upload/images